#!/usr/bin/env bash
# Install PostgreSQL on Ubuntu VPS and create isp_logserver database.
# Run on VPS as root: sudo bash deploy/vps-postgres-setup.sh
#
# Creates:
#   Database: isp_logserver
#   User:     isp_loguser
#   Password: from DB_PASSWORD env or auto-generated → saved to .db-credentials
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/isp-log-management}"
DB_NAME="${DB_NAME:-isp_logserver}"
DB_USER="${DB_USER:-isp_loguser}"
DB_PASSWORD="${DB_PASSWORD:-}"
CRED_FILE="${APP_DIR}/.db-credentials"

echo "==> VPS PostgreSQL setup (ISP Log Management)"

if ! command -v psql &>/dev/null; then
  apt-get update -y
  apt-get install -y postgresql postgresql-contrib
  systemctl enable postgresql
  systemctl start postgresql
fi

if [ -z "$DB_PASSWORD" ]; then
  if [ -f "$CRED_FILE" ]; then
    # shellcheck disable=SC1090
    source "$CRED_FILE"
    DB_PASSWORD="${DB_PASSWORD:-}"
  fi
fi

if [ -z "$DB_PASSWORD" ]; then
  DB_PASSWORD="$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 24)"
fi

echo "Creating role and database (idempotent)..."

sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
  ELSE
    ALTER ROLE ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
SQL

# PostgreSQL 15+ — schema permissions
sudo -u postgres psql -d "$DB_NAME" -v ON_ERROR_STOP=1 <<SQL
GRANT ALL ON SCHEMA public TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${DB_USER};
SQL

# Listen localhost only (apps on same VPS)
PG_CONF="$(sudo -u postgres psql -tAc "SHOW config_file;")"
PG_HBA="$(sudo -u postgres psql -tAc "SHOW hba_file;")"

if ! grep -q "127.0.0.1/32.*${DB_USER}" "$PG_HBA" 2>/dev/null; then
  echo "host    ${DB_NAME}    ${DB_USER}    127.0.0.1/32    scram-sha-256" >> "$PG_HBA"
fi

systemctl reload postgresql

mkdir -p "$APP_DIR"
cat > "$CRED_FILE" <<EOF
# Generated by deploy/vps-postgres-setup.sh — keep secret
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}
EOF
chmod 600 "$CRED_FILE"

echo ""
echo "=== PostgreSQL ready ==="
echo "  Database: ${DB_NAME}"
echo "  User:     ${DB_USER}"
echo "  Host:     127.0.0.1:5432"
echo "  Credentials saved: ${CRED_FILE}"
echo ""
echo "Next steps:"
echo "  cd ${APP_DIR}"
echo "  grep DATABASE_URL .db-credentials >> .env.production.local"
echo "  # or copy DATABASE_URL line into .env.production.local"
echo "  npm run db:setup"
echo "  npm run db:migrate"
echo "  npm run build:all && npm run pm2:restart"
